CREATE SCHEMA `diary` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
grant ALL ON diary.* TO phpuser@localhost;

CREATE TABLE `diary`.`T_DIARY_USERS` (
  `USER_NAME` VARCHAR(45) NOT NULL,
  `USER_PASSWORD` VARCHAR(45) NOT NULL,
  `DESC` VARCHAR(45) NULL,
  PRIMARY KEY (`USER_NAME`));

ALTER TABLE `diary`.`T_DIARY_USERS` 
ADD COLUMN `ROLE` INT NULL AFTER `DESC`;

CREATE TABLE `diary`.`T_ROLES` (
  `ROLE_NAME` VARCHAR(45) NOT NULL,
  `ROLE_DESC` VARCHAR(45) NULL,
  PRIMARY KEY (`ROLE_NAME`));

  
ALTER TABLE `diary`.`T_DIARY_USERS` 
CHANGE COLUMN `ROLE` `ROLE_NAME` VARCHAR(45) NULL DEFAULT NULL ;


ALTER TABLE `diary`.`T_DIARY_USERS` 
ADD INDEX `fk_T_DIARY_USERS_1_idx` (`ROLE_NAME` ASC);
ALTER TABLE `diary`.`T_DIARY_USERS` 
ADD CONSTRAINT `fk_T_DIARY_USERS_1`
  FOREIGN KEY (`ROLE_NAME`)
  REFERENCES `diary`.`T_ROLES` (`ROLE_NAME`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

INSERT INTO `diary`.`T_ROLES` (`ROLE_NAME`, `ROLE_DESC`) VALUES ('ADMIN', 'Diary Admin');
INSERT INTO `diary`.`T_ROLES` (`ROLE_NAME`, `ROLE_DESC`) VALUES ('USER', 'Normal user');

INSERT INTO `diary`.`T_DIARY_USERS` (`USER_NAME`, `USER_PASSWORD`, `DESC`, `ROLE_NAME`) VALUES ('nikhil', 'nikhil', '', 'ADMIN');
INSERT INTO `diary`.`T_DIARY_USERS` (`USER_NAME`, `USER_PASSWORD`, `DESC`, `ROLE_NAME`) VALUES ('nik', 'nik', '', 'USER');


CREATE TABLE `diary`.`T_DIARY` (
  `DIARY_ID` INT NOT NULL,
  `USER_NAME` VARCHAR(45) NOT NULL,
  `DATE` DATETIME NOT NULL,
  `SUBJECT` VARCHAR(45) NULL,
  `CONTENT` LONGTEXT NOT NULL,
  `FEELING` INT NULL,
  `TAG` INT NULL DEFAULT NULL,
  `ATTACHMENT` INT DEFAULT NULL,
  PRIMARY KEY (`DIARY_ID`));
  
CREATE TABLE `diary`.`T_FEELING` (
  `FEELING_ID` INT NOT NULL,
  `FEELTING_TYPE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`FEELING_ID`));
  
INSERT INTO `diary`.`T_FEELING` (`FEELING_ID`, `FEELTING_TYPE`) VALUES ('1', 'HAPPY');
INSERT INTO `diary`.`T_FEELING` (`FEELING_ID`, `FEELTING_TYPE`) VALUES ('2', 'SAD');

CREATE TABLE `diary`.`T_TAG` (
  `TAG_ID` INT NOT NULL,
  `TAG_NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TAG_ID`));

INSERT INTO `diary`.`T_TAG` (`TAG_ID`, `TAG_NAME`) VALUES ('1', 'PERSONAL');
INSERT INTO `diary`.`T_TAG` (`TAG_ID`, `TAG_NAME`) VALUES ('2', 'PROFESSIONAL');


  